# Site settings
title: Rust Belt Riders Composting | A Cleveland Worker Cooperative Working towards a more sustainable City
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rbr-cleveland.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
prose:
  media: images
  ignore:
    - .gitignore
    - _config.yml
    - /_layouts
    - /_sass
    - /geoms
    - /js
    - _includes
    - /bower_components
    - /css
    - /partials
    - bower.json
    - feed.xml
    - index.html
    - Readme.md
  metadata:
    _posts/faq:
      - name: "category"
        field:
          element: "hidden"
          value: "faq"
      - name: "layout"
        field:
          element: "hidden"
          value: "faq"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "faqtype"
        field:
          element: "select"
          label: "FAQ Section"
          options:
            - name: General
              value: general
            - name: Why Compost?
              value: compost
            - name: Why a Cooperative?
              value: coop
